### ISSUE TITLE
.cia Lockup at Loading Game and Sound, Suggestions

### ISSUE THREAD

**Issue by Smoker1** [elhobbs/prboom3ds#1]
![20150217_002812](https://cloud.githubusercontent.com/assets/8584462/6239811/811f421e-b6bc-11e4-8707-eddb5611a016.jpg)
The .3ds Copy works perfectly but as explained in the gbatemp Discussion Page.
The .cia Copy starts Loading, but locks up at some point. Do not know if it is continuing to Load or if it Crashed. But if you press the Home Button, it Crashes completely and have to Shut Down.

Edit
The .cia File now Installs and works perfectly like the .3ds File does. However, the Status Update Change says More Sound Updates, but there is none. More than likely, just something Minor.

Tested on Gateway EmuNAND 9.2 3DS 1st Gen Small

Suggestions:
For N3DS wondering if it is possible to use the Joystick for movement, the C Nub for turning/Looking, B for Jumping, X to Open/Interact, R to Fire, L to Aim, Y to Reload, ZL/ZR or the Directional Buttons Left and Right to Select Weapons, A to Jump. Keep the Keyboard on the Bottom Screen for Code Input/Naming Save Files. Also seeing if it would be possible to load .pk3 Files such as Brutal Doom/Hi Res Graphics.

**Comment by Smoker1** [comment]
![20150217_165741](https://cloud.githubusercontent.com/assets/8584462/6240707/fa690092-b6c6-11e4-9e4c-8069fc0f71e8.jpg)
No Sound

**Comment by Smoker1** [comment]
Also does not work on the N3DS XL (Aus Region)

**Comment by Smoker1** [comment]
![20150313_123235](https://cloud.githubusercontent.com/assets/8584462/6645994/fa31bf5a-c97d-11e4-9a71-9ac2b4900d32.jpg)
Everything is working fine up to this point. Then everything just locks up. Have to Hold the Power Button and start all over again.
Theory: It might be trying to start up the Music/Sound Files, but if they are not Present, it is crashing. But if it is looking into the WAD file for them, it might be too much for it to load at this point.
Also, there was a Issue with Doom Touch on Android I ran into before I got everything working. Apparently it was only compatible with the latest Version of Ultimate Doom (1.9)

**Comment by elhobbs** [comment]
Which version is this? It is not the latest. The startup messages for sound are missing. Are you building yourself or downloading from somewhere? Try downloading the latest from github. You may even need to go so far as removing the cia and then installing it again rather installing over the previous version. What are you using to install the cia?

**Comment by elhobbs** [comment]
The sound freeze issue appears to fixed and the controls are customizable through the menu. Saving control settings happens on exit now and the cstick and cpad are configurable now too.
