### ISSUE TITLE
Music doesn't sound like the origional

### ISSUE THREAD

**Issue by RadiantDerg** [elhobbs/prboom3ds#10]
It's as if not all instraments are there.

**Comment by FateForWindows** [comment]
I can definitely agree that it doesn't sound like the original, but for me it sounds like it was being played in DOSBox with the OPL synth instead of the epic original.

**Comment by elhobbs** [comment]
Posted a new release that addresses music and sfx issues. The music was being synthesized at the wrong rate. It still doesn't sound as good as the original but it sounds a lot better.

**Comment by FateForWindows** [comment]
Wait, this is back in development!? Wow!

**Comment by FateForWindows** [comment]
By the way, why the OPL synth and not something else?

**Comment by elhobbs** [comment]
Something else? Like what?
The benefit of opl synth from my perspective is that it uses the original mus files - no conversion tools/files required.

**Comment by FateForWindows** [comment]
Something that sounds a bit more like the music was intended to sound like, which was on the sc-55 (it sounded almost like the CD version).

**Comment by elhobbs** [comment]
Are you suggesting a hardware mod to add a sc-55? no? Perhaps you could be "a bit" more specific as to what you mean?

**Comment by FateForWindows** [comment]
I meant emulating something else, like the sc-55 or at least a soundfont.

**Comment by elhobbs** [comment]
I don't think the 3ds has enough memory to support a soundfont. The next best thing that it could support would be something converted to ogg or MP3. It would need to be be fairly low quality as the 3ds really is not powerful enough. And converted material leads into distributing copyright materials - which I don't want to do.
