### ISSUE TITLE
how to install cia

### ISSUE THREAD

**Issue by scorp1onSlayer** [elhobbs/prboom3ds#11]
how do you install the cia because i download it but all i get is a black screen

**Comment by ghost** [comment]
I have the same issue with the CIA version

**Comment by FateForWindows** [comment]
Install it from FBI.

**Comment by scorp1onSlayer** [comment]
Did you even read the issue

**Comment by ghost** [comment]
He clearly didnt.

**Comment by FateForWindows** [comment]
I was thinking it might have been a bad install :/ I'm having the issue now as well on the latest Luma nightly. If you're on that try downgrading to an older commit or 6.6.

**Comment by scorp1onSlayer** [comment]
im on 6.6 so i think i might need to go to 6.5 or 6.4

**Comment by FateForWindows** [comment]
It's working on 6.6 and the nightlies now. Are you all remembering to put the doom wads into the sd card root? You also need to move prboom.wad from prboom3ds-0.2.zip to the root of your SD Card.

**Comment by scorp1onSlayer** [comment]
oh ok thanks that might help i'll try your what your saying as i didnt know where to put them

**Comment by scorp1onSlayer** [comment]
there is no .wad in the prboom3ds-02.zip

**Comment by FateForWindows** [comment]
Weird, download it from the front page, it's there for sure.

**Comment by scorp1onSlayer** [comment]
can you send the file you have as i cant see what your talking about its also not in the master as i can see

**Comment by FateForWindows** [comment]
Very strange, thought it was in there.
I know the wad is also in prboom-3ds by devinacker in the data folder, so look there.
