### ISSUE TITLE
Crashing After a Specific Period of Time

### ISSUE THREAD

**Issue by ZL1LAC** [elhobbs/prboom3ds#15]
New 3DS, Running B9S 1.2, and Luma 8.0.

I don't have a log file for you sorry if there is a way I can get one let me know.

**Comment by elhobbs** [comment]
There seems to be a lot of system instability with b9s and Luma 8.
If you turn on exception handling and use the CIA version - then you will get a useful stack dump screen when it crashes. A screen shot of the crash dump screen is helpful. But until b9s and Luma 8 are a bit more stable then I would not bother.

**Comment by ZL1LAC** [comment]
@elhobbs I got a .dmp file if that helps?

**Comment by ZL1LAC** [comment]
I would like to note that the CIA version does this, if I boot into homebrew and use that version it doesn't happen BUT, I get no sound.

**Comment by ZL1LAC** [comment]
Found help to my issue elsewhere.
