### ISSUE TITLE
CIA won't save

### ISSUE THREAD

**Issue by SSQ123** [elhobbs/prboom3ds#17]
the CIA version will not save settings or save data every time I attempt to it says Save failed with no explanation as to why it failed. Did I do something wrong?

**Comment by moondisco** [comment]
you have to add files to this: download prboom3ds.smdh prboom.3dsx and prboom.3ds
then add these to a folder /3ds/prboom3ds/ 
if the folder doent exist then make one in the /3ds/ folder.
This should fix any issued, it did for me and saved my n3DS controller layout and saves.

**Comment by jcmejia** [comment]
The cia version of prboom 3ds wont save and it crashes if the folder is named prboom3ds

**Comment by elhobbs** [comment]
The version of prboom3ds from this site requires the wad files to be at /3ds/prboom3ds
It won’t work with any other folder path. 

I am thinking that you are using a version of prboom3ds created by someone else or maybe a really old version. Where did you get the prboom3ds.cia file?

**Comment by jcmejia** [comment]
After rebooting my new 3ds it stack dumps/crashes.

**Comment by jcmejia** [comment]
Yeah i fixed the problem with the saving but after restarting my 3ds
prboom3ds crashes this is the latest alpha version on your website
hopefully that bug gets fixed I really like prboom3ds gives the best doom
experience.

**Comment by elhobbs** [comment]
There are newer cia and 3dsx files directly in the repository. I did not get a lot of feedback on bug fixes so I did not bother putting it in the release section. You can give it a try and see if it fixes your issues.
