### ISSUE TITLE
Attempting to load graphic PWADs crash the game and music PWADS makes music silent.

### ISSUE THREAD

**Issue by JtheDuelist** [elhobbs/prboom3ds#22]
When I attempt to load a graphic mod PWAD using "files preloaded at game startup", the console crashes to the ARM crash screen, and when I attempt to use a music mod PWAD, the music is completely silent, some UI graphics disappear, and The touch screen for a split second displays the message "mus_load music: failed!". I don't know if this is a issue with prboom3ds itself or if the mods were made wrong. The mods work just fine in GZDoom on PC and Freedoom on Android.

**Comment by elhobbs** [comment]
Gzdoom is an enhanced doom engine. Prboom is not. Mods made for an enhanced engine will not work with prboom3ds.
Mods typically indicate whether they require an enhanced doom engine. 
Prboom3ds only supports the original doom music format. MP3 and other formats are not supported.
