### ISSUE TITLE
Ultimate Doom has no sound

### ISSUE THREAD

**Issue by lendunistus** [elhobbs/prboom3ds#23]
So when I play Ultimate Doom, Doom 2 or any of the Final Doom wads on prboom3ds, I don’t get any sort of audio, there’s no sfx or music of any kind. When I play the wads on PC using chocolate doom I don’t have this issue, and the shareware edition of Doom seems to work fine on prboom3ds.

**Comment by elhobbs** [comment]
You need to run the dspdump utility one time to extract the dsp binary. This is required for any/all homebrew audio to work. This only needs to be run once, but until you do there will be no audio in homebrew applications.

**Comment by lendunistus** [comment]
I have done the DSP Dump, and every other Homebrew application works fine. I have CFW and I installed the .cia version, hoping to play Doom on the go. The shareware wad works completely fine and plays all the audio (although it does crash very rarely). However, I run into the issue with no audio ONLY when I’m playing Ultimate Doom, Doom II and both of the Final Doom wads.

**Comment by elhobbs** [comment]
My guess would be these are modified wads with enhanced audio that is not compatible.
