### ISSUE TITLE
plutonia.wad and tnt.wad wont run

### ISSUE THREAD

**Issue by jcmejia** [elhobbs/prboom3ds#26]
How can I fix this 
![20190907_195334](https://user-images.githubusercontent.com/7544903/64481787-63780900-d1a9-11e9-9ee4-664e4c160133.jpg)

**Comment by elhobbs** [comment]
I would say that either the sd card is corrupt, the files are corrupt, or the files have been modified for an enhanced doom engine. 

I use the files that came with the original doom bundle from steam - and the all work fine. Where did you get the files?

**Comment by jcmejia** [comment]
From the steam version my sd card works fine for doom and doom 2 and other stuff on my n3ds but those wads wont run.

**Comment by jcmejia** [comment]
Unless ftp transfer corrupted the files.
