### ISSUE TITLE
Is it possible to change the music format to MP3 instead of using prboom's weak sound format? 

### ISSUE THREAD

**Issue by torizo237** [elhobbs/prboom3ds#29]
I understand the 3ds can't run certain midi format. But what if it was somehow changed to use MP3 sounds? Also, is PRboom the only compatible engine that the 3ds can utilize?

**Comment by elhobbs** [comment]
Yes, it is possible - but not something I am currently interested in doing. Feel free to generate a pull request with the required coding changes though.
