### ISSUE TITLE
I need some help, please.

### ISSUE THREAD

**Issue by wrecksauce** [elhobbs/prboom3ds#3]
I'm sorry this isn't really an issue, per se, but I need help. I for the life of me cannot figure out how to get this running on my 3DS. Any kind of guide or help would be much appreciated, thank you.

**Comment by wrecksauce** [comment]
Okay, nevermind, I got it running, but now the issue is that this resolution is way off. How would I go about changing it to a sharp res? I dont care if there are black bars around the screen.

**Comment by elhobbs** [comment]
Not sure what you are talking about with black bars around the screen. This runs in 3ds mode not ds mode and will always use the entire top screen. You can adjust the screen size which will change how big the world view window is displayed (and the edges are filled with a background image) - you can do this from the menu. If there are black bars then possibly you are using dsdoom? What are you using to launch?

If you played around too much in the menus (you can get weird results) then you can try deleting the configuration file- prboom.cfg. It will be in the same directory as prboom3ds.3dsx

**Comment by wrecksauce** [comment]
What i meant was, The resolution looks off. The font and Doomguys face have
extra pixels on them, and they don't look crisp. Its kind of hard to
explain, sorry. Hey, it works great, thats all that really matters, eh?
