### ISSUE TITLE
Hexen wads don’t  work

### ISSUE THREAD

**Issue by maxwell902** [elhobbs/prboom3ds#31]
Tried to load in some hexen, Chex quest and a voice wads and none of them show up

**Comment by elhobbs** [comment]
This version of prboom does not support Hexen. You should try Hexen instead - https://github.com/elhobbs/hexen/releases

The wad selector only shows iwads that it can use and only when they are present. There is no selector for pwads. they can be loaded through the menu though, but it is up to you to load the right pwad for the right iwad that you selected. 
I don’t believe Chex is supported.

**Comment by maxwell902** [comment]
What about Chex quest?

**Comment by elhobbs** [comment]
As I previously indicated - I do not know. 

Does it work with the pc version of prboom 2.5? If no then no. If yes then maybe. My guess is that it will not work.
