### ISSUE TITLE
iwad tag doom.wad not present 

### ISSUE THREAD

**Issue by starcestus** [elhobbs/prboom3ds#32]
I followed the instructions and im not sure why im getting this error no matter what i change i dont knnow what this tag is supposed to be. I think its this -iwad filename.wad but i dont know where to add it in the shortcut the instructions are not clear

**Comment by elhobbs** [comment]
It is not clear what “instructions” you followed. I assume you are trying to start prboom3ds while specify an iwad on the command line. That will not work. There is a builtin menu that will allow you to select from the supported iwads if they are present in the /3ds/prboom3ds directory. The detection is based on the original file names. So you can’t rename them with arbitrary names. See here for a list of supported names https://github.com/elhobbs/prboom3ds/blob/f8e545e6605dba3edd4482e3cf6b17be48d85a16/src/d_main.c#L128

**Comment by starcestus** [comment]
Windows Installation
--------------------

Just extract the zip to a directory of your choice and copy your IWAD
files into it. Now you can make shortcuts and add "-iwad filename.wad"
to them.

The SDL_mixer library used by PrBoom supports software MIDI music
synthesis. If you want to hear the Doom music, you need a set of
Timidity instrument patches. Do a web search for timidity patch sets,
there are plenty around.
These patch sets are a large download (>5megs).
SDL_mixer does not currently support hardware MIDI synthesis. But we
have added a hacked version of SDL_mixer with native midi support. If
you like to try it out, rename SDL_mixer_beta.dll to SDL_mixer.dll.
You should rename the original SDL_mixer.dll before. Tell us if it
works or not. Please note, that there might be bugs in the native midi
implementation.

These instructions I'm trying to I have room. Doom.wad and doom2.wad both give the error and no matter where I put the files I get the error I presented previously. I don't know what I'm doing wrong but these wads work on gzdoom so I know they are good
