### ISSUE TITLE
Iwad tag doom. Was not found

### ISSUE THREAD

**Issue by starcestus** [elhobbs/prboom3ds#33]
It is not clear what “instructions” you followed. I assume you are trying to start prboom3ds while specify an iwad on the command line. That will not work. There is a builtin menu that will allow you to select from the supported iwads if they are present in the /3ds/prboom3ds directory. The detection is based on the original file names. So you can’t rename them with arbitrary names. See here for a list of supported names https://github.com/elhobbs/prboom3ds/blob/f8e545e6605dba3edd4482e3cf6b17be48d85a16/src/d_main.c#L128

_Originally posted by @elhobbs in https://github.com/elhobbs/prboom3ds/issues/32#issuecomment-599805506_

Windows Installation
Just extract the zip to a directory of your choice and copy your IWAD
files into it. Now you can make shortcuts and add "-iwad filename.wad"
to them.

The SDL_mixer library used by PrBoom supports software MIDI music
synthesis. If you want to hear the Doom music, you need a set of
Timidity instrument patches. Do a web search for timidity patch sets,
there are plenty around.
These patch sets are a large download (>5megs).
SDL_mixer does not currently support hardware MIDI synthesis. But we
have added a hacked version of SDL_mixer with native midi support. If
you like to try it out, rename SDL_mixer_beta.dll to SDL_mixer.dll.
You should rename the original SDL_mixer.dll before. Tell us if it
works or not. Please note, that there might be bugs in the native midi
implementation.

These instructions I'm trying to I have room. Doom.wad and doom2.wad both give the error and no matter where I put the files I get the error I presented previously. I don't know what I'm doing wrong but these wads work on gzdoom so I know they are good. I'm not sure what it is I'm doing wrong move the files to the prboom3ds directory and get the error

**Comment by starcestus** [comment]
I can get to the was selection menu but when I select a wad it gives me that error and freezes the system

**Comment by elhobbs** [comment]
Try deleting the prboom.cfg file. If you copied it from a pc it can cause issues. Essentially have only the wad files (including doom and the prboom wad) and the 3dsx file in the /3ds/prboom3ds folder. 
Also those are the pc instructions. They won’t work on the 3ds.

**Comment by starcestus** [comment]
I dont have that .cfg i am downloading the zip from here https://github.com/elhobbs/prboom3ds and moving everything to the  /3ds/prboom3ds directory. i feel like im missing something obvious

**Comment by elhobbs** [comment]
Are you using the cia or the 3dsx version? How are you launching it? What versions for firmware and hax? Make sure you are using the latest prboom3ds version from the releases section (0.7-alpha) https://github.com/elhobbs/prboom3ds/releases

Please provide a complete directory listing for the files in /3ds/prboom3ds 

Where did you get the doom wad files? Prboom3ds is not an enhanced engine. So it will not support wad files modified for gzdoom etc.

**Comment by starcestus** [comment]
The CIA version but i tried running it from FBI as well 
Luma 3ds V10.0.1
Im using Wads i got from doom3bfg edition
![image](https://user-images.githubusercontent.com/62255109/76862486-91af6300-6834-11ea-8f69-dafb217a8ad5.png)

I tried doom64 but ive tried it without that in there

just downloaded the files from the link you provided and still got the same error

**Comment by starcestus** [comment]
The wads from the Doom3 BFG edition dont work on this engine for some reason, i am sorry for wasting your time
