### ISSUE TITLE
prboom.wad

### ISSUE THREAD

**Issue by discapes** [elhobbs/prboom3ds#34]
I placed my doom1.wad in /3ds/prboom3ds/, and prboom found it, but next it said it couldnt find prboom.wad

Please don't close this like you closed the other pull request, I really can't find any mention of prboom.wad in the readme.

**Comment by elhobbs** [comment]
Read the installation instructions here https://github.com/elhobbs/prboom3ds/releases
I did not see a pull request and since this is prboom it has the same requirements. prboom.wad is a required file.

**Comment by discapes** [comment]
Sorry I mean issue

**Comment by elhobbs** [comment]
Were you able to read the instructions and resolve your issue?

**Comment by discapes** [comment]
Yeah. thanks
