### ISSUE TITLE
External wads wont work

### ISSUE THREAD

**Issue by ghost** [elhobbs/prboom3ds#36]
Can you make it so you can open diffrent wads instead of the original ones

**Comment by elhobbs** [comment]
Your request is unclear. Prboom itself is capable of loading pwads - or partial conversion wads using the menu. It is only compatible with vanilla wads that work with the dos version of doom or doom 2. This does not support wads that require an enhanced doom engine. If it requires gzdoom then it won’t work.

**Comment by ghost** [comment]
in prboom3ds retroarch you can load things like vanilla brutal doom

**Comment by elhobbs** [comment]
This should support that as well. Did you receive an error message? Again there is a menu to specify wad files and deh files. It is up to you to put the files in the right place. Generally this is the same place you put the doom wad files?

**Comment by ghost** [comment]
it actually didnt show it at all

**Comment by SpergParagon** [comment]
I think NexisNecro is referring to a method of loading PWADs that would be more convenient than editing the config file. A frontend, for example.

**Comment by elhobbs** [comment]
A menu aside from the prboom menu that already does this?
