### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xXSabreXx** [elhobbs/prboom3ds#37]
it says freedoom2.wad not found but i have the doom2.wad file in the main file??? please help

**Comment by xXSabreXx** [comment]
now i put the freedoom2.wad in the main file and it still doesnt work

**Comment by xXSabreXx** [comment]
i even tried the doom2.wad

**Comment by xXSabreXx** [comment]
it is the cia also

**Comment by elhobbs** [comment]
Freedom is a full conversion wad it can only be selected by the initial launch window. The option to launch will only show if you put the freedoom1.wad or freedoom2.wad files in the /3ds/prboom3ds directory. The file names need to match exactly. In other words - the files are recognized by name - not by content. If you mess with the file names then things will likely not work as expected.

**Comment by xXSabreXx** [comment]
Do I need to rename them?

**Comment by xXSabreXx** [comment]
Because I got the freedoom2.wad file now

**Comment by xXSabreXx** [comment]
Do I need to rename the freedoom2.wad file?

**Comment by xXSabreXx** [comment]
i have figured it out!
