### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by xXSabreXx** [elhobbs/prboom3ds#38]
What bit should i use 8bit 15bit 16bit or 32bit? o3ds

**Comment by elhobbs** [comment]
The only one implemented is 8bit - I would use that one :)

I never created a proper release but the prboom3ds.3dsx file in the master branch only has 8bit and wide as options. The wide mode disables 3D but it changes the horizontal resolution from 400 to 800. Personally I can not tell the difference. But it is there if you want to try it.
