### ISSUE TITLE
Game crashes when attempting to load intro.

### ISSUE THREAD

**Issue by frozenLake** [elhobbs/prboom3ds#4]
Hey, I've been having issues with getting this to run with ironhax: no matter what IWAD I load, it doesn't seem to want to work. I have tried doom2.wad, freedoom2.wad, and chex.wad renamed to doom.wad, hex edited to be considered a proper iwad. It manages to get to loading the music, and then it freezes, playing the same first note repeatedly. it gives the numbers "8744 0 9846" with doom2.wad, and "8599 0 9701" with freedoom2.wad, with added varying spacing, which makes me assume it is connected to the music. This is with the files avaliable on the n3ds branch, so I believe I am up to the current version.

**Comment by elhobbs** [comment]
N3ds branch is the latest. I have used doom doom2 and freedom 1&2 with ironhax and they all work fine. Do you have the prboom.wad file in the same directory?

**Comment by frozenLake** [comment]
Yes, all of the wad files are in the folder with the 3dsx. (unless I'm using the incorrect prboom.wad or something)

Is there some sort of debug version that would save logs?

**Comment by elhobbs** [comment]
My initial thought is that you are using a really old version. Those numbers look like sound buffer positions that I had left in for debugging. But they are not present in the current build. Try downloading the latest version again and loading it. If that does not work try taking a video of the screens during startup. A lot of messages fly by and it is hard to read them quickly.

**Comment by frozenLake** [comment]
Well, github does say that the latest version is from April, so I don't know if its glitching over there, but I'll redownload and try to get it working.

**Comment by frozenLake** [comment]
Sorry it took so long to get the video, hopefully it helps

https://www.youtube.com/watch?v=lH8HLEuE0Xg&feature=youtu.be

**Comment by elhobbs** [comment]
You have enabled 32 bit rendering. Which doesn't work. This either happened because you turned it on in the menu or you copied a prboom.cfg file from a pc. I recommend that you delete the prboom.cfg file from the 3ds sd card.

**Comment by frozenLake** [comment]
That fixed it, thank you!
