### ISSUE TITLE
Game only utilizes half of 3DS top screen's width

### ISSUE THREAD

**Issue by KristopherHall** [elhobbs/prboom3ds#45]
The width of the game is at 400p, while the 3DS supports up to 800p. Couldn't find a way to change this as changing the _screen_width_ parameter in the _prboom.cfg_ file does nothing. This causes text to be blurry.

**Comment by elhobbs** [comment]
I never created a release but if you build the master branch the option is available in the menus. I could not really see a difference though so I lost interest.
