### ISSUE TITLE
3DS XL input not working properly

### ISSUE THREAD

**Issue by kevansevans** [elhobbs/prboom3ds#5]
Currently having issues playing this build. None of the 3DS buttons make anything happen besides the start opening up menu. Currently only way to navigate is with they bottom screen keyboard and tapping the corresponding shortcut key to jump to the menu item I want, then tapping 'a'. IE if I want options, I tap 'o' on the keyboard to move to options, then tap 'a' to open the options. Also I am only capable of reassigning one key, which is forward. This does take 3ds input, as I am able to assign the slider up to forward. However that's all I can change in terms of input, as the arrow keys on the keyboard don't do anything.

I'm not sure if this is the fact I have a 3DS XL, or it's the current firmware I have installed (10.1.0-27U), or I'm using the wrong files. Thanks regardless.

**Comment by elhobbs** [comment]
Not sure about 10.1. I haven't updated yet. Works fine on my n3ds xl. Did you copy the prboom.cfg file from a pc or other system? Either way try deleting the cfg file and trying again.

**Comment by kevansevans** [comment]
The config file I'm using is the one the build auto-generates. I even tried
using the .cfg from a different build of prboom3ds that does have input
working correctly, and it did not work.

On Friday, September 18, 2015, elhobbs notifications@github.com wrote:

> Not sure about 10.1. I haven't updated yet. Works fine on my n3ds xl. Did
> you copy the prboom.cfg file from a pc or other system? Either way try
> deleting the cfg file and trying again.
> 
> Sent from my iPhone
> 
> > On Sep 18, 2015, at 12:31 PM, kevansevans <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > 
> > Currently having issues playing this build. None of the 3DS buttons make
> > anything happen besides the start opening up menu. Currently only way to
> > navigate is with they bottom screen keyboard and tapping the corresponding
> > shortcut key to jump to the menu item I want, then tapping 'a'. IE if I
> > want options, I tap 'o' on the keyboard to move to options, then tap 'a' to
> > open the options. Also I am only capable of reassigning one key, which is
> > forward. This does take 3ds input, as I am able to assign the slider up to
> > forward. However that's all I can change in terms of input, as the keys on
> > the keyboard don't do anything.
> > 
> > I'm not sure if this is the fact I have a 3DS XL, or it's the current
> > firmware I have installed (10.1.0-27U), or I'm using the wrong files.
> > Thanks regardless.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/elhobbs/prboom3ds/issues/5#issuecomment-141593305.

## 

```
               \      _     /
```

___________(0)_/__________/

```
      O   O   (_](.)[_)   O   O

                      O
```

**Comment by elhobbs** [comment]
Yes, the intent was to let it create a new one with default values. It is possible to get the key bindings messed up by choosing invalid values in the key binding setup options such that you cannot change the key bindings. Removing the cfg files would restore the default key setup. 

How are you launching prboom3ds? Ninjhax, ironhax, tubehax? And is this an old or new 3ds?

Also, please make sure you are using the latest build https://github.com/elhobbs/prboom3ds?files=1
Several people have had similar issues that were resolved by downloading the latest version ( even if you have it already) and copying it to the 3ds again.

**Comment by kevansevans** [comment]
I am using tubehax to launch homebrew and I'm on old 3ds xl. When I get the
chance I'll remove the files and try to run it again.

On Saturday, September 19, 2015, elhobbs notifications@github.com wrote:

> Yes, the intent was to let it create a new one with default values. It is
> possible to get the key bindings messed up by choosing invalid values in
> the key binding setup options such that you cannot change the key bindings.
> Removing the cfg files would restore the default key setup.
> 
> How are you launching prboom3ds? Ninjhax, ironhax, tubehax? And is this an
> old or new 3ds?
> 
> Also, please make sure you are using the latest build
> https://github.com/elhobbs/prboom3ds?files=1
> Several people have had similar issues that were resolved by downloading
> the latest version ( even if you have it already) and copying it to the 3ds
> again.
> 
> Sent from my iPhone
> 
> > On Sep 19, 2015, at 5:46 AM, kevansevans <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > 
> > The config file I'm using is the one the build auto-generates. I even
> > tried
> > using the .cfg from a different build of prboom3ds that does have input
> > working correctly, and it did not work.
> > 
> > On Friday, September 18, 2015, elhobbs <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > 
> > > Not sure about 10.1. I haven't updated yet. Works fine on my n3ds xl.
> > > Did
> > > you copy the prboom.cfg file from a pc or other system? Either way try
> > > deleting the cfg file and trying again.
> > > 
> > > Sent from my iPhone
> > > 
> > > > On Sep 18, 2015, at 12:31 PM, kevansevans <notifications@github.com
> > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> > > > 
> > > > Currently having issues playing this build. None of the 3DS buttons
> > > > make
> > > > anything happen besides the start opening up menu. Currently only way
> > > > to
> > > > navigate is with they bottom screen keyboard and tapping the
> > > > corresponding
> > > > shortcut key to jump to the menu item I want, then tapping 'a'. IE if I
> > > > want options, I tap 'o' on the keyboard to move to options, then tap
> > > > 'a' to
> > > > open the options. Also I am only capable of reassigning one key, which
> > > > is
> > > > forward. This does take 3ds input, as I am able to assign the slider
> > > > up to
> > > > forward. However that's all I can change in terms of input, as the
> > > > keys on
> > > > the keyboard don't do anything.
> > > > 
> > > > I'm not sure if this is the fact I have a 3DS XL, or it's the current
> > > > firmware I have installed (10.1.0-27U), or I'm using the wrong files.
> > > > Thanks regardless.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/elhobbs/prboom3ds/issues/5#issuecomment-141593305
> > > .
> > 
> > ## 
> > 
> > \ _ /
> > 
> > ___________(0)_/__________/
> > 
> > O O (_](.)[_) O O
> > 
> > O
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/elhobbs/prboom3ds/issues/5#issuecomment-141643122.

## 

```
               \      _     /
```

___________(0)_/__________/

```
      O   O   (_](.)[_)   O   O

                      O
```
