### ISSUE TITLE
no music

### ISSUE THREAD

**Issue by Anathema30** [elhobbs/prboom3ds#8]
all in title. Will it be on work again to have music or the project is dead?

**Comment by elhobbs** [comment]
The music works fine. You may need to run the dsp dump utility depending on the version of prboom3ds and/or your 3ds version.

**Comment by Anathema30** [comment]
Latest prboom available. I ran the dsp dump utility, im supposed to do what now?

**Comment by elhobbs** [comment]
Is any sound working? Make sure you have the volume up for both the 3ds and the music and sfx volume in prboom3ds in the options. 
If it still doesn't work let me know what you have for a setup o3ds/n3ds custom firmware versions etc.

**Comment by Anathema30** [comment]
Gunfire, monster etc work fine, it's just the music that doesn't play for some reason.
Im on n3ds xl 11.0, no cfw just using web browser bypass and have menuhax as another entry.
That's why it's bit weird. The game run smoothly, gun noise, monster, door etc.. Just the music refusing to join the party xD

**Comment by elhobbs** [comment]
Both the sfx and music use the same method to play sound. I do not have anything on version 11 to verify with though. You could try both the latest release and the prior version from github to see if either one works. If I remember correctly on of them uses CSND and the other uses Dsp.

**Comment by Anathema30** [comment]
Im getting prboom.wad not found - cannot continue when trying to use the one from github

**Comment by elhobbs** [comment]
That file is required. It should be in the same directory as the 3dsx file or in the root directory if you are using cia. Not sure where you got the other prboom3ds binary from but all version that I built require the prboom.wad file.
